version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=dev
    networks:
      - symfony

  nginx:
    image: nginx:stable
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony

  frontend-react:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: react
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - symfony

volumes:
  db-data:

networks:
  symfony:
    driver: bridge
