version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
    networks:
      - symfony

  nginx:
    image: nginx:stable
    container_name: symfony_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - symfony

  frontend-react:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: react
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "${REACT_PORT}:3000"
    command: npm start
    networks:
      - symfony

volumes:
  db-data:

networks:
  symfony:
    driver: bridge
